<?php

namespace App\Http\Controllers;

use App\Models\Degree; // Assuming you have a Degree model
use App\Models\User;   // Assuming you have a User model
use App\Models\University; // Assuming you have a University model
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage; // For file downloads
// use App\Services\BlockchainService; // Uncomment this line once you create the BlockchainService

class DegreeController extends Controller
{
    /**
     * Display a listing of the degrees.
     * This might show all degrees for super_admin, or only university's degrees for university_admin.
     */
    public function index(): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        $user = Auth::user();
        $degrees = collect(); // Initialize as an empty collection

        if ($user->isSuperAdmin()) {
            $degrees = Degree::all();
        } elseif ($user->isUniversityAdmin()) {
            // Fetch degrees issued by the university the admin belongs to
            $degrees = Degree::where('university_id', $user->university_id)->get();
        }
        // Students will likely view their degrees via their dashboard or a dedicated student route

        return view('degrees.index', compact('degrees'));
    }

    /**
     * Show the form for creating a new degree.
     * Only university admins should be able to issue degrees.
     */
    public function create(): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        // Fetch students and universities for the form
        $students = User::where('role', 'student')->get();
        // For a university admin, they should only see their own university or be pre-selected for it
        $universities = University::all(); // Adjust if university admin should only see their own university

        return view('degrees.create', compact('students', 'universities'));
    }

    /**
     * Store a newly created degree in storage.
     * This is where you would integrate blockchain logic to generate the hash and tx_id.
     */
    public function store(Request $request): \Illuminate\Http\RedirectResponse
    {
        // Validate the request data
        $validatedData = $request->validate([
            'user_id' => 'required|exists:users,id',
            'university_id' => 'required|exists:universities,id',
            'title' => 'required|string|max:255',
            'major' => 'nullable|string|max:255',
            'graduation_date' => 'required|date', // Assuming this is the field from migration
            // 'degree_hash' and 'tx_id' will be generated by blockchain integration
        ]);

        // --- Blockchain Integration Placeholder ---
        // In a real application, you would call your blockchain service here.
        // This service would:
        // 1. Take degree details as input.
        // 2. Interact with your smart contract to mint the degree.
        // 3. Return a unique hash (degree_hash) and a transaction ID (tx_id).
        // For now, we'll use placeholders:
        $blockchainDegreeHash = 'generated_blockchain_hash_' . uniqid(); // Placeholder
        $blockchainTxId = 'generated_tx_id_' . uniqid(); // Placeholder

        // If you uncommented `use App\Services\BlockchainService;`
        // try {
        //     $blockchainResult = BlockchainService::issueDegree($validatedData);
        //     $blockchainDegreeHash = $blockchainResult['hash'];
        //     $blockchainTxId = $blockchainResult['tx_id'];
        // } catch (\Exception $e) {
        //     return redirect()->back()->withInput()->withErrors(['blockchain' => 'Failed to issue degree on blockchain: ' . $e->getMessage()]);
        // }
        // --- End Blockchain Integration Placeholder ---

        $degree = Degree::create(array_merge($validatedData, [
            'degree_hash' => $blockchainDegreeHash,
            'tx_id' => $blockchainTxId,
            'status' => 'issued', // Initial status
        ]));

        return redirect()->route('degrees.index')->with('success', 'Degree issued successfully! Blockchain hash: ' . $degree->degree_hash);
    }

    /**
     * Display the specified degree.
     */
    public function show(Degree $degree): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        return view('degrees.show', compact('degree'));
    }

    /**
     * Show the form for editing the specified degree.
     */
    public function edit(Degree $degree): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {
        $students = User::where('role', 'student')->get();
        $universities = University::all();
        return view('degrees.edit', compact('degree', 'students', 'universities'));
    }

    /**
     * Update the specified degree in storage.
     */
    public function update(Request $request, Degree $degree): \Illuminate\Http\RedirectResponse
    {
        $validatedData = $request->validate([
            'user_id' => 'required|exists:users,id',
            'university_id' => 'required|exists:universities,id',
            'title' => 'required|string|max:255',
            'major' => 'nullable|string|max:255',
            'graduation_date' => 'required|date',
            'status' => 'required|string|in:issued,verified,revoked', // Allow status update
        ]);

        $degree->update($validatedData);

        return redirect()->route('degrees.index')->with('success', 'Degree updated successfully!');
    }

    /**
     * Remove the specified degree from storage.
     */
    public function destroy(Degree $degree): \Illuminate\Http\RedirectResponse
    {
        $degree->delete();
        return redirect()->route('degrees.index')->with('success', 'Degree deleted successfully!');
    }

    /**
     * Download the certificate for the specified degree.
     * In a real application, this would fetch the actual certificate file,
     * potentially from IPFS or a secure storage linked by the blockchain hash.
     */
    public function downloadCertificate(Degree $degree): \Symfony\Component\HttpFoundation\StreamedResponse
    {
        // For demonstration, let's assume certificates are stored in storage/app/certificates
        // and named after their degree_hash.pdf
        $filePath = 'certificates/' . $degree->degree_hash . '.pdf';

        if (Storage::exists($filePath)) {
            return Storage::download($filePath, 'certificate_' . $degree->user->name . '_' . $degree->title . '.pdf');
        } else {
            // Handle case where certificate file does not exist
            abort(404, 'Certificate file not found.');
        }
    }
}
